apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "psmdb-operator.fullname" . }}
---
{{- if .Values.watchAllNamespaces }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding	kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "psmdb-operator.fullname" . }}
  {{- if .Values.watchNamespace }}
  namespace: {{ .Values.watchNamespace }}
  {{- end }}
  labels:
{{ include "psmdb-operator.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "psmdb-operator.fullname" . }}
  {{- if .Values.watchNamespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  {{- if (or .Values.watchAllNamespaces .Values.watchNamespace) }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ include "psmdb-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
